import React from "react";

function SubThreecol() {
  return (
    <>
      <section
        class="
                                      elementor-section
                                      elementor-top-section
                                      elementor-element
                                      elementor-element-48aae45
                                      rey-section-stretched
                                      elementor-section-full_width
                                      elementor-section-gap-no
                                      rey-mobiOffset
                                      elementor-section-height-default
                                      elementor-section-height-default
                                    "
        data-id="48aae45"
        data-element_type="section"
      >
        <div
          class="
                                        elementor-container
                                        elementor-column-gap-no
                                      "
        >
          <div
            class="
                                          elementor-column
                                          elementor-col-33
                                          elementor-top-column
                                          elementor-element
                                          elementor-element-2eb1d6a
                                        "
            data-id="2eb1d6a"
            data-element_type="column"
          >
            <div
              class="
                                            elementor-column-wrap--2eb1d6a
                                            elementor-widget-wrap
                                            elementor-element-populated
                                          "
            >
              <div
                class="
                                              elementor-element
                                              elementor-element-41cd6e8
                                              el-mark--hp
                                              elementor-widget
                                              elementor-widget-heading
                                            "
                data-id="41cd6e8"
                data-element_type="widget"
                data-widget_type="heading.default"
              >
                <div class="elementor-widget-container">
                  <h2
                    class="
                                                  elementor-heading-title
                                                  elementor-size-default
                                                "
                  >
                    Casual <mark>Dresses </mark>
                  </h2>
                </div>
              </div>
            </div>
          </div>
          <div
            class="
                                          elementor-column
                                          elementor-col-33
                                          elementor-top-column
                                          elementor-element
                                          elementor-element-3b5f84a
                                        "
            data-id="3b5f84a"
            data-element_type="column"
          >
            <div
              class="
                                            elementor-column-wrap--3b5f84a
                                            elementor-widget-wrap
                                            elementor-element-populated
                                          "
            >
              <div
                class="
                                              elementor-element
                                              elementor-element-d4ab41d
                                              el-mark--hp
                                              elementor-widget
                                              elementor-widget-heading
                                            "
                data-id="d4ab41d"
                data-element_type="widget"
                data-widget_type="heading.default"
              >
                <div class="elementor-widget-container">
                  <h2
                    class="
                                                  elementor-heading-title
                                                  elementor-size-default
                                                "
                  >
                    Shirts &amp;
                    <mark>Blouses</mark>
                  </h2>
                </div>
              </div>
            </div>
          </div>
          <div
            class="
                                          elementor-column
                                          elementor-col-33
                                          elementor-top-column
                                          elementor-element
                                          elementor-element-c45e895
                                        "
            data-id="c45e895"
            data-element_type="column"
          >
            <div
              class="
                                            elementor-column-wrap--c45e895
                                            elementor-widget-wrap
                                            elementor-element-populated
                                          "
            >
              <div
                class="
                                              elementor-element
                                              elementor-element-f48c9ae
                                              el-mark--hp
                                              elementor-widget
                                              elementor-widget-heading
                                            "
                data-id="f48c9ae"
                data-element_type="widget"
                data-widget_type="heading.default"
              >
                <div class="elementor-widget-container">
                  <h2
                    class="
                                                  elementor-heading-title
                                                  elementor-size-default
                                                "
                  >
                    <mark> Jumpsuits </mark>
                  </h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default SubThreecol;
