import React from "react";

function TwoCol({ url1, url2 }) {
  return (
    <>
      <section
        class="
                                      elementor-section
                                      elementor-top-section
                                      elementor-element
                                      elementor-element-71f0240
                                      rey-section-stretched
                                      elementor-section-full_width
                                      elementor-section-gap-no
                                      rey-mobiOffset
                                      elementor-section-height-default
                                      elementor-section-height-default
                                    "
        data-id="71f0240"
        data-element_type="section"
      >
        <div
          class="
                                        elementor-container
                                        elementor-column-gap-no
                                      "
        >
          <div
            class="
                                          elementor-column
                                          elementor-col-50
                                          elementor-top-column
                                          elementor-element
                                          elementor-element-a8f9702
                                        "
            data-id="a8f9702"
            data-element_type="column"
          >
            <div
              class="
                                            elementor-column-wrap--a8f9702
                                            elementor-widget-wrap
                                            elementor-element-populated
                                          "
            >
              <div
                class="
                                              elementor-element
                                              elementor-element-60e2497
                                              elementor-widget
                                              elementor-widget-image
                                            "
                data-id="60e2497"
                data-element_type="widget"
                data-widget_type="image.default"
              >
                <div class="elementor-widget-container">
                  <a href="https://ivloo.com/jeans-clothing/">
                    <img
                      width="500"
                      height="669"
                      src={url1}
                      class="
                                                    attachment-full
                                                    size-full
                                                  "
                      alt=""
                      loading="lazy"
                      sizes="(max-width: 500px) 100vw, 500px"
                    />
                  </a>
                </div>
              </div>
            </div>
          </div>
          <div
            class="
                                          elementor-column
                                          elementor-col-50
                                          elementor-top-column
                                          elementor-element
                                          elementor-element-0a47d18
                                        "
            data-id="0a47d18"
            data-element_type="column"
          >
            <div
              class="
                                            elementor-column-wrap--0a47d18
                                            elementor-widget-wrap
                                            elementor-element-populated
                                          "
            >
              <div
                class="
                                              elementor-element
                                              elementor-element-db1e036
                                              elementor-widget
                                              elementor-widget-image
                                            "
                data-id="db1e036"
                data-element_type="widget"
                data-widget_type="image.default"
              >
                <div class="elementor-widget-container">
                  <a href="https://ivloo.com/shorts-clothing/">
                    <img
                      width="500"
                      height="669"
                      src={url2}
                      class="
                                                    attachment-large
                                                    size-large
                                                  "
                      alt=""
                      loading="lazy"
                      sizes="(max-width: 500px) 100vw, 500px"
                    />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default TwoCol;
